export const INITIAL_LISTINGS = [
  {
    id: 1,
    type: "Hotel",
    title: "Roltek Hotel & Resort",
    address: "25/B Milford Road, NY",
    price: 11245,
    views: 55555,
    publishOn: "Sep 21, 2024",
    status: "Active",
  },
  {
    id: 2,
    title: "Skyline Airways Booking",
    address: "25/B Milford Road, NY",
    price: 11245,
    type: "Flight",
    views: 55555,
    publishOn: "Sep 21, 2024",
    status: "Active",
  },
  {
    id: 3,
    title: "Venetian Canal Cruiser Rental",
    address: "25/B Milford Road, NY",
    price: 11245,
    type: "Car",
    views: 55555,
    publishOn: "Sep 21, 2024",
    status: "Expired",
  },
  {
    id: 4,
    title: "Metropolis Grand Suites",
    address: "25/B Milford Road, NY",
    price: 11245,
    type: "Hotel",
    views: 55555,
    publishOn: "Sep 21, 2024",
    status: "Active",
  },
  {
    id: 5,
    title: "Golden Dunes Desert Cruise",
    address: "25/B Milford Road, NY",
    price: 11245,
    type: "Cruise",
    views: 55555,
    publishOn: "Sep 21, 2024",
    status: "Expired",
  },
  {
    id: 6,
    title: "Coastal Breeze Beach Resort",
    address: "25/B Milford Road, NY",
    price: 11245,
    type: "Hotel",
    views: 55555,
    publishOn: "Sep 21, 2024",
    status: "Active",
  },
  {
    id: 7,
    title: "Alpine Peaks Mountain Lodge",
    address: "12/C Ridgeway Ave, CO",
    price: 9840,
    type: "Hotel",
    views: 55555,
    publishOn: "Aug 14, 2024",
    status: "Active",
  },
  {
    id: 8,
    title: "Desert Rose Convertible",
    address: "8/A Palm Street, AZ",
    price: 4200,
    type: "Car",
    views: 55555,
    publishOn: "Jul 30, 2024",
    status: "Expired",
  },
  {
    id: 9,
    title: "Northern Lights Express",
    address: "3/D Aurora Blvd, AK",
    price: 15600,
    type: "Flight",
    views: 55555,
    publishOn: "Jun 02, 2024",
    status: "Active",
  },
  {
    id: 10,
    title: "Mediterranean Pearl Cruise",
    address: "19/B Harbor View, FL",
    price: 21300,
    type: "Cruise",
    views: 55555,
    publishOn: "May 18, 2024",
    status: "Active",
  },
];